package it.maramb.adix.entity.permits;

public enum UserPermits {
    ADMIN_VIEW_ALL_USERS,
    ADMIN_ADD_USER,
    ADMIN_EDIT_USER,
    ADMIN_EDIT_USER_PERMITS,
    ADMIN_EDIT_USER_CREDENTIALS,
    ADMIN_DELETE_USER,
    ANY_ROLE_VIEW_ALL_CUSTOMERS,
    ANY_ROLE_ADD_CUSTOMER,
    ANY_ROLE_EDIT_CUSTOMER,
    ANY_ROLE_DELETE_CUSTOMER,
    ANY_ROLE_VIEW_ALL_FULFILLMENTS,
    ANY_ROLE_ADD_FULFILLMENT,
    ANY_ROLE_EDIT_FULFILLMENT,
    ANY_ROLE_DELETE_FULFILLMENT,
    ROLE_PARTNER_VIEW_OWN_CUSTOMERS,
    ROLE_INSPECTOR_VIEW_OWN_CUSTOMERS,
    ROLE_RESPONSIBLE_VIEW_OWN_CUSTOMERS,
    ROLE_ACCOUNTANT_VIEW_OWN_CUSTOMERS,
    ANY_ROLE_VIEW_OWN_FULFILLMENTS_RECORDS,
    ANY_ROLE_EDIT_OWN_FULFILLMENTS_RECORDS,
    ANY_ROLE_VIEW_ALL_FULFILLMENTS_RECORDS,
    ANY_ROLE_EDIT_ALL_FULFILLMENTS_RECORDS;

    public class Constants {
        public static final String ADMIN_VIEW_ALL_USERS = "ADMIN_VIEW_ALL_USERS";
        public static final String ADMIN_ADD_USER = "ADMIN_ADD_USER";
        public static final String ADMIN_EDIT_USER = "ADMIN_EDIT_USER";
        public static final String ADMIN_EDIT_USER_PERMITS = "ADMIN_EDIT_USER_PERMITS";
        public static final String ADMIN_EDIT_USER_CREDENTIALS = "ADMIN_EDIT_USER_CREDENTIALS";
        public static final String ADMIN_DELETE_USER = "ADMIN_DELETE_USER";
        public static final String ANY_ROLE_VIEW_ALL_CUSTOMERS = "ANY_ROLE_VIEW_ALL_CUSTOMERS";
        public static final String ANY_ROLE_ADD_CUSTOMER = "ANY_ROLE_ADD_CUSTOMER";
        public static final String ANY_ROLE_EDIT_CUSTOMER = "ANY_ROLE_EDIT_CUSTOMER";
        public static final String ANY_ROLE_DELETE_CUSTOMER = "ANY_ROLE_DELETE_CUSTOMER";
        public static final String ANY_ROLE_VIEW_ALL_FULFILLMENTS = "ANY_ROLE_VIEW_ALL_FULFILLMENTS";
        public static final String ANY_ROLE_ADD_FULFILLMENT = "ANY_ROLE_ADD_FULFILLMENT";
        public static final String ANY_ROLE_EDIT_FULFILLMENT = "ANY_ROLE_EDIT_FULFILLMENT";
        public static final String ANY_ROLE_DELETE_FULFILLMENT = "ANY_ROLE_DELETE_FULFILLMENT";
        public static final String ROLE_PARTNER_VIEW_OWN_CUSTOMERS = "ROLE_PARTNER_VIEW_OWN_CUSTOMERS";
        public static final String ROLE_INSPECTOR_VIEW_OWN_CUSTOMERS = "ROLE_INSPECTOR_VIEW_OWN_CUSTOMERS";
        public static final String ROLE_RESPONSIBLE_VIEW_OWN_CUSTOMERS = "ROLE_RESPONSIBLE_VIEW_OWN_CUSTOMERS";
        public static final String ROLE_ACCOUNTANT_VIEW_OWN_CUSTOMERS = "ROLE_ACCOUNTANT_VIEW_OWN_CUSTOMERS";
        public static final String ANY_ROLE_VIEW_OWN_FULFILLMENTS_RECORDS = "ANY_ROLE_VIEW_OWN_FULFILLMENTS_RECORDS";
        public static final String ANY_ROLE_EDIT_OWN_FULFILLMENTS_RECORDS = "ANY_ROLE_EDIT_OWN_FULFILLMENTS_RECORDS";
        public static final String ANY_ROLE_VIEW_ALL_FULFILLMENTS_RECORDS = "ANY_ROLE_VIEW_ALL_FULFILLMENTS_RECORDS";
        public static final String ANY_ROLE_EDIT_ALL_FULFILLMENTS_RECORDS = "ANY_ROLE_EDIT_ALL_FULFILLMENTS_RECORDS";
    }

    public static Boolean isAdminAuthority(UserPermits permit) {
        return permit.toString().startsWith("ADMIN_");
    }
}
